#!/usr/bin/env bash
#
# Entrypoint script for Zulip development container
#
# This script:
# 1. Fixes permissions for mounted volumes (runs as root initially)
# 2. Waits for required services (PostgreSQL, Redis, RabbitMQ, Memcached)
# 3. Sets up secrets configuration
# 4. Runs provision if needed
# 5. Initializes the database
# 6. Starts the development server (as zulip user)

set -e

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

log_info() {
    echo -e "${GREEN}[INFO]${NC} $1"
}

log_warn() {
    echo -e "${YELLOW}[WARN]${NC} $1"
}

log_error() {
    echo -e "${RED}[ERROR]${NC} $1"
}

# Fix permissions for mounted directories
fix_permissions() {
    log_info "Fixing permissions for mounted volumes..."

    # Ensure the zulip user owns necessary directories
    chown -R zulip:zulip /home/zulip

    # Make the entire /srv/zulip writable by zulip user
    # This is necessary because pnpm and other tools need to write temp files
    chown -R zulip:zulip /srv/zulip

    log_info "Permissions fixed!"
}

# Wait for a service to be ready
wait_for_service() {
    local host=$1
    local port=$2
    local service=$3
    local max_attempts=${4:-30}
    local attempt=1

    log_info "Waiting for $service at $host:$port..."

    while ! nc -z "$host" "$port" 2>/dev/null; do
        if [ $attempt -ge $max_attempts ]; then
            log_error "$service at $host:$port is not available after $max_attempts attempts"
            exit 1
        fi
        log_info "Attempt $attempt/$max_attempts: $service not ready, waiting..."
        sleep 2
        ((attempt++))
    done

    log_info "$service is ready!"
}

# Wait for PostgreSQL to accept connections
wait_for_postgres() {
    local max_attempts=${1:-30}
    local attempt=1

    log_info "Waiting for PostgreSQL to accept connections..."

    while ! pg_isready -h "${PGHOST:-database}" -U "${PGUSER:-zulip}" -q 2>/dev/null; do
        if [ $attempt -ge $max_attempts ]; then
            log_error "PostgreSQL is not accepting connections after $max_attempts attempts"
            exit 1
        fi
        log_info "Attempt $attempt/$max_attempts: PostgreSQL not ready, waiting..."
        sleep 2
        ((attempt++))
    done

    log_info "PostgreSQL is ready!"
}

# Setup development secrets file
setup_secrets() {
    local secrets_file="/srv/zulip/zproject/dev-secrets.conf"
    local template_file="/srv/zulip/docker/dev-secrets.conf"

    if [ ! -f "$secrets_file" ]; then
        log_info "Creating development secrets file..."
        if [ -f "$template_file" ]; then
            # Use the pre-configured template with Docker-compatible passwords
            cp "$template_file" "$secrets_file"
            log_info "Secrets file copied from template"
        else
            # Fallback: create with Docker-compatible passwords
            cat > "$secrets_file" << EOF
[secrets]
local_database_password = ${LOCAL_DATABASE_PASSWORD:-zulip_dev_password}
rabbitmq_password = ${RABBITMQ_PASSWORD:-zulip_dev_password}
initial_password_salt = docker_dev_initial_password_salt_not_for_production
avatar_salt = docker_dev_avatar_salt_not_for_production_use
shared_secret = docker_dev_shared_secret_not_for_production_use_only
secret_key = docker_dev_secret_key_not_for_production_use_only_50chars
camo_key = docker_dev_camo_key_not_for_production_use_only
zulip_org_key = docker_dev_org_key_not_for_production_use_only
zulip_org_id = 00000000-0000-0000-0000-000000000001
altcha_hmac = docker_dev_altcha_hmac_key_not_for_production
EOF
            log_info "Secrets file created with default values"
        fi
    else
        log_info "Secrets file already exists at $secrets_file"
    fi
}

# Create custom development settings to override database/service hosts
setup_custom_dev_settings() {
    local custom_settings="/srv/zulip/zproject/custom_dev_settings.py"

    if [ ! -f "$custom_settings" ] || ! grep -q "Docker development" "$custom_settings" 2>/dev/null; then
        log_info "Creating custom development settings for Docker..."
        cat > "$custom_settings" << 'EOF'
# Docker development environment settings
# Auto-generated by entrypoint-dev.sh

import os

# Database configuration - connect to Docker PostgreSQL
DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": os.environ.get("PGDATABASE", "zulip"),
        "USER": os.environ.get("PGUSER", "zulip"),
        "PASSWORD": os.environ.get("LOCAL_DATABASE_PASSWORD", "zulip_dev_password"),
        "HOST": os.environ.get("PGHOST", "database"),
        "PORT": os.environ.get("PGPORT", "5432"),
        "CONN_MAX_AGE": 600,
        "OPTIONS": {
            "connect_timeout": 10,
        },
    }
}

# Memcached - connect to Docker memcached (no auth in dev)
MEMCACHED_LOCATION = os.environ.get("MEMCACHED_LOCATION", "memcached:11211")
MEMCACHED_USERNAME = None

# Redis - connect to Docker Redis (no auth in dev)
REDIS_HOST = os.environ.get("REDIS_HOST", "redis")

# RabbitMQ - connect to Docker RabbitMQ
RABBITMQ_HOST = os.environ.get("RABBITMQ_HOST", "rabbitmq")

# External host for browser access
if os.environ.get("EXTERNAL_HOST"):
    EXTERNAL_HOST = os.environ["EXTERNAL_HOST"]
    REALM_HOSTS = {"zulip": EXTERNAL_HOST}
EOF
        log_info "Custom settings created at $custom_settings"
    else
        log_info "Custom settings file already exists"
    fi
}

# Initialize the database if needed
init_database() {
    log_info "Checking database initialization..."

    # Ensure venv is activated
    activate_venv

    # Check if database exists and has tables
    if ! PGPASSWORD="${PGPASSWORD}" psql -h "${PGHOST:-database}" -U "${PGUSER:-zulip}" -d "${PGDATABASE:-zulip}" -c '\dt' 2>/dev/null | grep -q 'zerver_'; then
        log_info "Database needs initialization..."

        # Create the database schema using Django migrations
        log_info "Running database migrations..."
        python ./manage.py migrate --noinput

        # Generate initial data
        log_info "Generating realm and initial data..."
        python ./manage.py generate_realm_creation_link 2>/dev/null || true

        log_info "Database initialization complete!"
    else
        log_info "Database already initialized, running migrations..."
        python ./manage.py migrate --noinput
    fi
}

# Activate virtual environment
activate_venv() {
    if [ -f ".venv/bin/activate" ]; then
        log_info "Activating virtual environment..."
        # shellcheck disable=SC1091
        source .venv/bin/activate
    fi
}

# Run initial provision steps (without system package installation)
run_provision_steps() {
    log_info "Running provision steps..."

    # Install Python dependencies if venv doesn't exist
    if [ ! -d ".venv" ] || [ ! -f ".venv/bin/python" ]; then
        log_info "Setting up Python virtual environment..."
        uv sync --frozen
    else
        log_info "Python virtual environment exists, syncing dependencies..."
        uv sync --frozen
    fi

    # Activate the virtual environment for subsequent commands
    activate_venv

    # Install Node.js dependencies if node_modules doesn't exist
    if [ ! -d "node_modules" ] || [ ! -f "node_modules/.pnpm/lock.yaml" ]; then
        log_info "Installing Node.js dependencies..."
        corepack pnpm install --frozen-lockfile
    else
        log_info "Node.js dependencies exist"
    fi

    # Generate secrets (requires venv to be active)
    log_info "Generating secrets..."
    python ./scripts/setup/generate_secrets.py --development

    # Create the UUID file for development if it doesn't exist
    # This is normally created by provision, but we handle it here for Docker
    local uuid_file="/srv/.zulip-dev-uuid"
    if [ ! -f "$uuid_file" ]; then
        log_info "Creating development UUID file..."
        python3 -c "import uuid; print(uuid.uuid4())" | sudo tee "$uuid_file" > /dev/null
    fi

    # Create var directories
    mkdir -p var/coverage var/log var/node-coverage var/test_uploads var/uploads var/xunit-test-results var/run

    # Build emoji if needed (check for actual generated file)
    if [ ! -f "static/generated/emoji/emoji_codes.json" ]; then
        log_info "Building emoji..."
        ./tools/setup/emoji/build_emoji
    fi

    # Build pygments data if needed
    if [ ! -f "web/generated/pygments_data.json" ]; then
        log_info "Building pygments data..."
        ./tools/setup/build_pygments_data
    fi

    # Build timezone data if needed
    if [ ! -f "web/generated/timezones.json" ]; then
        log_info "Building timezone data..."
        ./tools/setup/build_timezone_values
    fi

    # Compile messages if needed
    if [ ! -f "locale/language_name_map.json" ]; then
        log_info "Compiling messages..."
        python ./manage.py compilemessages --ignore='*'
    fi

    log_info "Provision steps complete!"
}

# Configure RabbitMQ user and vhost
configure_rabbitmq() {
    log_info "RabbitMQ configuration is handled by Docker environment variables"
    # The rabbitmq container is configured with RABBITMQ_DEFAULT_USER and RABBITMQ_DEFAULT_PASS
    # No additional configuration needed
}

# Run as zulip user
run_as_zulip() {
    if [ "$(id -u)" = "0" ]; then
        exec gosu zulip "$@"
    else
        exec "$@"
    fi
}

# Main setup logic (runs as root to fix permissions, then as zulip)
main() {
    log_info "Starting Zulip development container..."
    log_info "Working directory: $(pwd)"
    log_info "Running as user: $(id)"

    # Change to the zulip directory
    cd /srv/zulip

    # If running as root, fix permissions first
    if [ "$(id -u)" = "0" ]; then
        fix_permissions

        # Re-run this script as the zulip user
        log_info "Switching to zulip user..."
        exec gosu zulip "$0" "$@"
    fi

    # From here on, we're running as the zulip user

    # Wait for all required services
    wait_for_service "${PGHOST:-database}" 5432 "PostgreSQL"
    wait_for_postgres
    wait_for_service "${REDIS_HOST:-redis}" 6379 "Redis"
    wait_for_service "${RABBITMQ_HOST:-rabbitmq}" 5672 "RabbitMQ"
    wait_for_service "${MEMCACHED_LOCATION%%:*}" "${MEMCACHED_LOCATION##*:}" "Memcached"

    # Setup configuration
    setup_secrets
    setup_custom_dev_settings

    # Run provision steps
    run_provision_steps

    # Initialize database
    init_database

    # Configure RabbitMQ (if needed)
    configure_rabbitmq

    log_info "Starting development server..."
    log_info "Access Zulip at http://${EXTERNAL_HOST:-localhost:8007}"

    # Execute the command passed to the container
    exec "$@"
}

# Run main function
main "$@"
